#!/usr/bin/env zsh

source "$DOTFILES/aliases.zsh"
source $HOME/.local/share/zsh/plugins/local/ascii_font/ascii_font.plugin.zsh

text='orrans'

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

ascii-text -W -B -c rainbow $text

if [[ ! -z $extra_echo ]]; then
  echo
  echo
fi

unset -f ascii-text
