#!/bin/sh
# Alacritty is a Windows application and reads %APPDATA%\alacritty\alacritty.toml
# and nothing else — the stow symlinks under ~/.config/alacritty are invisible to
# it. Generate that entry file so it imports windows.toml from this checkout and
# launches the WSL distro.
#
# Runs either from inside WSL or from Git Bash on Windows.
# With --check, writes nothing and exits non-zero when the file is missing or stale.
set -eu

check_only=0
if [ "${1:-}" = "--check" ]; then
	check_only=1
fi

cfg_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if command -v wslpath >/dev/null 2>&1; then
	to_win() { wslpath -w "$1"; }
	to_unix() { wslpath -u "$1"; }
elif command -v cygpath >/dev/null 2>&1; then
	to_win() { cygpath -m "$1"; }
	to_unix() { cygpath -u "$1"; }
else
	echo "install-windows.sh: needs wslpath (WSL) or cygpath (Git Bash)" >&2
	exit 1
fi

appdata=${APPDATA:-}
if [ -z "$appdata" ]; then
	# cmd.exe refuses a UNC working directory, so ask from a drive-backed one
	appdata=$(cd /mnt/c 2>/dev/null || cd /; cmd.exe /c 'echo %APPDATA%' 2>/dev/null | tr -d '\r\n')
fi
if [ -z "$appdata" ]; then
	echo "install-windows.sh: cannot resolve %APPDATA%" >&2
	exit 1
fi

dest_dir="$(to_unix "$appdata")/alacritty"
dest="$dest_dir/alacritty.toml"

distro=${WSL_DISTRO_NAME:-}
if [ -z "$distro" ] && command -v wsl.exe >/dev/null 2>&1; then
	distro=$(wsl.exe -l -q 2>/dev/null | tr -d '\0\r' | grep -v '^$' | grep -vi '^docker-desktop' | head -1)
fi

# Win32 and TOML both accept forward slashes, including in the \\wsl.localhost prefix
import=$(to_win "$cfg_dir/windows.toml" | tr '\\' '/')

zsh_win="C:/Program Files/Git/usr/bin/zsh.exe"
if [ -x /usr/bin/zsh.exe ] && command -v cygpath >/dev/null 2>&1; then
	zsh_win=$(to_win /usr/bin/zsh.exe)
fi

generated=$(
	echo "# Generated by .config/alacritty/install-windows.sh. Do not edit by hand."
	echo "# Fonts, colors and key bindings come from the imported file; edit them in the dotfiles repo."
	echo
	echo "[general]"
	echo "import = [\"$import\"]"
	echo
	echo "[env]"
	echo 'MSYSTEM = "MINGW64"'
	echo 'CHERE_INVOKING = "1"'
	echo
	if [ -n "$distro" ]; then
		echo "# Shell: WSL ($distro). To use the Git Bash zsh instead, swap the two blocks."
		echo "[terminal.shell]"
		echo 'program = "wsl.exe"'
		echo "args = [\"-d\", \"$distro\", \"--cd\", \"~\"]"
		echo
		echo "# [terminal.shell]"
		echo "# program = \"$zsh_win\""
		echo '# args = ["-l"]'
	else
		echo "# Shell: zsh from Git for Windows, as a login shell so /etc/profile sets up PATH"
		echo "[terminal.shell]"
		echo "program = \"$zsh_win\""
		echo 'args = ["-l"]'
	fi
)

if [ "$check_only" -eq 1 ]; then
	[ -f "$dest" ] || exit 1
	[ "$(cat "$dest")" = "$generated" ] || exit 1
	exit 0
fi

mkdir -p "$dest_dir"
if [ -f "$dest" ] && ! grep -q "Generated by" "$dest"; then
	echo "Backing up existing $dest -> $dest.bak" >&2
	cp -f "$dest" "$dest.bak"
fi
printf '%s\n' "$generated" >"$dest"
echo "Alacritty entry config written to $dest (imports $import, shell: ${distro:-Git Bash zsh})"
